### ISSUE TITLE
v1.2.x roadmap

### ISSUE THREAD

**Issue by maxfierke** [OfficeStack/OpenSkedge#95]
- [ ] PHP 5.6, PHP 7 support (#107)
- [ ] Refactor ludicrous data structures (schedules, availability, etc.)
- [ ] Introduce maintainable schedule view
- [ ] Cleanup navigation
- [ ] Migrate UI to Bootstrap 3
- [ ] More tests (#48) 
- [ ] Add announcements feature (#76)
- [ ] Allow time clock/hour reporting on current week (#97)

Since more people seem to be using OpenSkedge these days, it's probably worth it to clean up a lot of the code and fix some of the major pain points that prevent others from getting involved.
